/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./index.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "background-primary": "#FFFFFF",
        "background-card": "#F5F5F5",
        "labels-primary": "#000000",
        primary: "#27272A",
        caption: "#9CA3AF",
        "tab-unselected": "#999999",
        "tab-selected": "#000000",
        "icon-primary": "#333333",
        "weather-sun": "#EDA36E",
        "weather-cloud": "#8AA2D7",
        "status-button": "#27272A",
        "tint-active": "#ECFDF5",
        "tint-grace": "#FEF2F2",
        "tint-critical": "#FFF1F2",
        "state-active": "#10B981",
        "state-grace": "#FB923C",
        "state-critical": "#EF4444",
        "border-state-active": "#DCFCE7",
        "border-state-grace": "#FFEDD5",
        "border-state-critical": "#FFE4E6",
        alert: "#FA8B46",
        overlay: "rgba(0, 0, 0, 0.4)",
        "tint-alert-banner": "#FFF7ED",
        "chart-axis": "#71717A",
        "chart-line": "#767676",
        "chart-grid": "#E5E5E5",
        "chart-tooltip": "#000000",
        "chart-tooltip-text": "#FFFFFF",
        "history-card": "#FAFAF9",
        "status-safe": "#10B981",
        "status-warning": "#EF4444",
        "chevron-muted": "#B0B3BA",
        "profile-subtitle": "#71717A",
        separator: "#E5E5E5",
      },
      borderRadius: {
        card: "20px",
        button: "100px",
        modal: "34px",
      },
      borderWidth: {
        bar: "0.33px",
      },
      boxShadow: {
        button: "0px 4px 8px 1px rgba(56, 91, 61, 0.25)",
        "state-active": "0px 2px 4px 0px rgba(42, 165, 42, 0.30)",
        "state-grace": "0px 2px 4px 0px rgba(165, 114, 42, 0.30)",
        "state-critical": "0px 2px 4px 0px rgba(165, 42, 42, 0.30)",
      },
      fontSize: {
        tab: ["10px", { lineHeight: "1" }],
      },
    },
  },
  plugins: [],
};
